### ISSUE TITLE
0.6.4在node5.x安装报错

### ISSUE THREAD

**Issue by xuexb** [ecomfe/fecs#159]
发现升级`fecs@0.6.4`后测试时在node5.x报错，但在linux环境下可以继续执行，windows环境直接退出，[linux测试](https://travis-ci.org/xuexb/key-cache/jobs/117742447)，[windows测试](https://ci.appveyor.com/project/xuexb/key-cache/build/46/job/oh4plwxtj2xc8ywf)

在真机中node5.7下直接`npm i fecs`也报，如：
```
npm install fecs
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> spawn-sync@1.0.15 postinstall /home/local/node_modules/spawn-sync
> node postinstall


> fecs@0.6.4 postinstall /home/local/node_modules/fecs
> node scripts/install.js

inject eslint.js...
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './node_modules/eslint/lib/eslint.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/local/node_modules/fecs/scripts/install.js:18:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
```

node 5.7, npm 3.6

---

经测试`fecs@0.6.3`无该问题，是否考虑添加node不同版本的测试，和windows环境的测试

**Comment by chriswong** [comment]
看起来是因为 npm3 安装所有模块扁平化导致的，我测试下

**Comment by chriswong** [comment]
@xuexb  试试 fecs@0.6.5-beta.5 或 fecs@beta

**Comment by xuexb** [comment]
@chriswong 赞，测试通过：

> [linux测试](https://travis-ci.org/xuexb/key-cache/builds/117986177), [windows测试](https://ci.appveyor.com/project/xuexb/key-cache/build/50)

**Comment by xuexb** [comment]
还有不知道为啥，感觉 [fecs官网](http://fecs.baidu.com) 底部的`© 2015 Baidu EFE`中的2015怪怪的...
