### ISSUE TITLE
检查js文件会报以下错误

### ISSUE THREAD

**Issue by jingchaofang** [ecomfe/fecs#258]
```
/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:103
        throw err
        Ü

TypeError: Cannot read property 'match' of undefined
    at getNamespace (/usr/local/lib/node_modules/fecs/node_modules/eslint/lib/config/plugins.js:40:22)
    at Object.load (/usr/local/lib/node_modules/fecs/node_modules/eslint/lib/config/plugins.js:110:33)
    at Array.forEach (native)
    at Object.exports.registerPlugins (/usr/local/lib/node_modules/fecs/lib/js/rules/index.js:51:13)
    at Checker.checker.check (/usr/local/lib/node_modules/fecs/lib/js/checker.js:41:11)
    at /usr/local/lib/node_modules/fecs/lib/checker.js:95:35
    at wrappedMapper (/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:96:21)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
```

**Comment by ielgnaw** [comment]
麻烦提供下你的 js 文件吧
如果 github 不方便上传，请将文件发送到 wuji0223@126.com ，谢谢~

**Comment by chriswong** [comment]
先看你的使用方法
