### ISSUE TITLE
node v5.10.1 下执行 报错

### ISSUE THREAD

**Issue by kokokele** [ecomfe/fecs#259]
js git:(zp_riot) fecs 

/usr/local/lib/node_modules/.fecs_npminstall/manis/0.3.1/manis/lib/util.js:134
        throw e;
        ^
YAMLException: Cannot read config file: /Users/antz/Documents/baidu/nuomi-b-sap/supplier-web/.fecsrc
Error: missed comma between flow collection entries in "/Users/antz/Documents/baidu/nuomi-b-sap/supplier-web/.fecsrc" at line 5, column 21:
                "indent": 0,
                        ^
    at generateError (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:168:9)
    at readFlowCollection (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:688:7)
    at composeNode (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:1328:11)
    at readFlowCollection (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:716:7)
    at composeNode (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:1328:11)
    at readFlowCollection (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:716:7)
    at composeNode (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:1328:11)
    at readBlockMapping (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:1004:16)
    at composeNode (/usr/local/lib/node_modules/.fecs_npminstall/js-yaml/3.7.0/js-yaml/lib/js-yaml/loader.js:1327:12)

**Comment by ielgnaw** [comment]
看看你的 .fecsrc 文件内容~~

**Comment by chriswong** [comment]
错误信息指出是少了逗号，YAML 基本上不需要逗号，所以很可能是你某处多了逗号，然后需要更多的逗号

**Comment by kokokele** [comment]
{
    "eslint": {
        "env": {
                "browser": true,
                "es6": true
            },
        "parser": "babel-eslint",

        "rules": {
            "no-unused-vars": 1，
            "indent": 0,
            "space-before-blocks": 0,
            "block-spacing": 0,
            "space-before-function-paren": 0,
            "no-extra-semi": 0,
            "semi-spacing": 0,
            "no-tabs": 0,
            "quotes": 0
        }
    }
}

**Comment by chriswong** [comment]
> "no-unused-vars": 1，
全角逗号

**Comment by kokokele** [comment]
多谢
