### ISSUE TITLE
npm install后运行报错

### ISSUE THREAD

**Issue by branjing** [ecomfe/fecs#267]
/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:103
        throw err
        ^
Error
    at generateError (/usr/local/lib/node_modules/fecs/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/local/lib/node_modules/fecs/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDocument (/usr/local/lib/node_modules/fecs/node_modules/js-yaml/lib/js-yaml/loader.js:1509:5)
    at loadDocuments (/usr/local/lib/node_modules/fecs/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at load (/usr/local/lib/node_modules/fecs/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
    at Object.safeLoad (/usr/local/lib/node_modules/fecs/node_modules/js-yaml/lib/js-yaml/loader.js:1580:10)
    at Finder.exports.loader (/usr/local/lib/node_modules/fecs/node_modules/manis/lib/util.js:130:21)
    at /usr/local/lib/node_modules/fecs/node_modules/manis/lib/finder.js:81:39
    at findConfigs (/usr/local/lib/node_modules/fecs/node_modules/manis/lib/finder.js:135:26)
    at Finder.from (/usr/local/lib/node_modules/fecs/node_modules/manis/lib/finder.js:76:27)

**Comment by leeight** [comment]
node版本太低了吧
