### ISSUE TITLE
fecs 报错，无法运行

### ISSUE THREAD

**Issue by li-yinan** [ecomfe/fecs#302]
重装node、brew、nvm均无效，删除全局的node_modules无效，删除所有npm相关配置无效。。。
```
/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:103
        throw err
        ^

Error: Failed to load plugin jest: Cannot find module 'eslint-plugin-jest'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.load (/usr/local/lib/node_modules/fecs/node_modules/eslint/lib/config/plugins.js:134:29)
    at Array.forEach (native)
    at Object.exports.registerPlugins (/usr/local/lib/node_modules/fecs/lib/js/rules/index.js:51:13)
    at Checker.checker.check (/usr/local/lib/node_modules/fecs/lib/js/checker.js:43:11)
    at /usr/local/lib/node_modules/fecs/lib/checker.js:95:35
    at wrappedMapper (/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/usr/local/lib/node_modules/fecs/node_modules/map-stream/index.js:96:21)
    at Stream.ondata (internal/streams/legacy.js:16:26)
```
```
node --version
v8.0.0
```
```
npm --version
5.0.1
```

**Comment by li-yinan** [comment]
手动安装eslint和eslint-plugin-jest后运行fecs出现奇怪的提示
```
fecs  INFO src/app.js (21 messages)
fecs ERROR → line 9, col 1: Definition for rule 'import/no-named-as-default-member' was not found
fecs ERROR → line 9, col 1: Definition for rule 'babel/new-cap' was not found
fecs ERROR → line 9, col 1: Definition for rule 'import/no-unresolved' was not found
fecs ERROR → line 9, col 1: Definition for rule 'import/named' was not found
fecs ERROR → line 9, col 1: Definition for rule 'import/default' was not found
fecs ERROR → line 9, col 1: Definition for rule 'import/namespace' was not found
fecs ERROR → line 9, col 1: Definition for rule 'import/no-absolute-path' was not found
```

**Comment by chriswong** [comment]
安装的 fecs 和 eslint 是什么版本？

**Comment by li-yinan** [comment]
```
fecs --version
fecs 1.4.1
```
```
eslint --version
v4.4.1
```

**Comment by chriswong** [comment]
fecs@1.4.1 还不支持 eslint@4.x，现在正在测试的 fecs@beta 支持

正常安装的话，fecs@1.4.1 应该不会用 eslint@4.x 的

**Comment by jinzhubaofu** [comment]
fecs 现在不会安装 `eslint-plugin-jest` / `eslint-plugin-flowtype` 这种插件包，导致在检测这些文件时会查找不到。
