### ISSUE TITLE
sudo npm install fecs -g 报错

### ISSUE THREAD

**Issue by Junior2Ran** [ecomfe/fecs#321]
```bash
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/fecs -> /usr/local/lib/node_modules/fecs/bin/fecs

> fecs@1.5.5 postinstall /usr/local/lib/node_modules/fecs
> node scripts/install.js --allow-root

inject eslint.js...
fs.js:766
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/fecs/node_modules/eslint/lib/linter.js' -> '/usr/local/lib/node_modules/fecs/node_modules/eslint/lib/linter.js.bak'
    at Object.fs.renameSync (fs.js:766:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/fecs/scripts/install.js:20:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

node版本 v8.11.1
npm版本 5.6.0

**Comment by win7killer** [comment]
mark

**Comment by zhengxkq** [comment]
npm config set unsafe-perm=true

**Comment by Phinome** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions 官方解答

**Comment by hzz780** [comment]
> npm config set unsafe-perm=true

Good jod.
