### ISSUE TITLE
fecs format 报错

### ISSUE THREAD

**Issue by sundyxfan** [ecomfe/fecs#66]
ecs format

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'next' of null
    at Object.exports.fix (/usr/local/lib/node_modules/fecs/node_modules/jformatter/lib/fix.js:45:34)
    at Object.format (/usr/local/lib/node_modules/fecs/node_modules/jformatter/jformatter.js:313:39)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/fecs/lib/js/formatter.js:80:53)

**Comment by ishowshao** [comment]
可不可以把原文件发给我

发自我的 iPhone

**Comment by ishowshao** [comment]
@sundyxfan 需要被格式的源文件来定位错误，可不可以把源文件发给我

**Comment by sundyxfan** [comment]
搞定了 谢谢

**Comment by ishowshao** [comment]
@sundyxfan 我想知道是啥文件导致的报错...

**Comment by zengguanming** [comment]
ubuntu14.04, node v0.10.33　报错了
-----------------------
fecs format

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Line 1: Unexpected token (
    at throwError (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:1213:9)
    at parseVariableIdentifier (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2081:13)
    at /home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parseFunctionDeclaration (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2884:14)
    at /home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parseSourceElement (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3055:24)
    at parseSourceElements (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3095:29)
    at parseProgram (/home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3109:19)
    at /home/zengguanming/.nvm/v0.10.33/lib/node_modules/fecs/node_modules/jformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38

**Comment by ishowshao** [comment]
好像是遇到了有语法错误的文件，最新版给做了个catch，语法错误的文件直接不format了
