### ISSUE TITLE
fecs format 文件夹时报了可能产生内存泄露的警告

### ISSUE THREAD

**Issue by 81735595** [ecomfe/fecs#76]
报了一个警告，但是格式化成功了。
具体原因是 lib/formatter.js:115 注册的事件没有被清除，在done里加了个removeListener就行了，因为不太会用github所以不会提交修改……(T_T)……要是没时间改告诉我具体提交流程也行，我的hi是ouwanqu

**Comment by chriswong** [comment]
这个是用 once 注册的，自动清除

**Comment by chriswong** [comment]
提交修改的流程：

1. 先点右上角 `Fork` 按钮，fork 到你自己的 github 账号下。

2. git clone 你账号下刚 fork 的 repo 到本地，修改后提交。

3. 到 https://github.com/ecomfe/fecs/pulls 页右上有个绿色的 `New pull request` 按钮，点击之后进到选择比较的分支，选择适当的分支，提交 `pull request` 即可。

**Comment by 81735595** [comment]
但是如果once不执行就不会清除了……once绑定的时error事件，所以如果没错误的话，事件绑的就会越来越多……再附个错误报告吧……

(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at once (events.js:204:8)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/fecs/lib/formatter.js:115:23)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/fecs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
fecs: 864ms

**Comment by 81735595** [comment]
ok，我试一下
